/**
 * Soniox's built-in voice roster for `tts-rt-v2`, with the metadata its
 * voice library exposes: gender, perceived age, accent, use-case tags and
 * style tags.
 *
 * GENERATED — do not hand-edit. Re-run:
 *   SONIOX_API_KEY=snx_proj_... node scripts/fetch-soniox-voices.mjs
 * See that script for why this is a snapshot rather than a runtime fetch.
 *
 * Source: GET /v1/shared-voices?model=tts-rt-v2
 * Fetched: 2026-09-10 — 200 voices
 */

/** Perceived speaker gender, as Soniox classifies it. */
export type SonioxVoiceGender = 'male' | 'female' | 'neutral';

/** Perceived speaker age, as Soniox classifies it. */
export type SonioxVoiceAge = 'young' | 'middle_aged' | 'old';

export interface SonioxVoiceProfile {
  /** The string sent in the TTS `voice` field. Also the display label. */
  id: string;
  gender: SonioxVoiceGender;
  age: SonioxVoiceAge;
  /** Free-form in the API (e.g. `american`, `british`); see SONIOX_ACCENTS. */
  accent: string;
  /** What the voice is suited for (`narration`, `conversational`, …). */
  useCase: string[];
  /** How the voice sounds (`warm`, `energetic`, …). */
  style: string[];
  /** Soniox's own one-line character description. English only — Soniox
   *  publishes no translations, so the picker shows it verbatim. */
  description: string;
}

export const SONIOX_VOICE_ROSTER: SonioxVoiceProfile[] = [
  { id: "Daniel", gender: "male", age: "middle_aged", accent: "british",
    useCase: ["narration", "entertainment", "educational"], style: ["calm", "deep", "smooth", "friendly"],
    description: "Low British baritone that sits still and lets the facts do the work. Built for documentaries, explainers, and other long, even reads." },
  { id: "Nina", gender: "female", age: "young", accent: "british",
    useCase: ["social_media", "conversational"], style: ["energetic", "friendly", "neutral", "smooth", "bright"],
    description: "Young British speaker with bounce in the phrasing and an easy, matey warmth. Made for social clips and casual conversation." },
  { id: "Emma", gender: "female", age: "young", accent: "british",
    useCase: ["conversational", "social_media"], style: ["bright", "friendly", "energetic"],
    description: "Offhand British delivery with a light lift at the ends of lines. Sounds like someone you would actually text back." },
  { id: "Adrian", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["educational", "narration", "entertainment", "social_media", "conversational"], style: ["deep", "smooth", "calm", "neutral", "confident", "formal"],
    description: "A deep, focused male voice with crisp articulation, measured pacing, and a composed tone that feels authoritative, clear, and professional." },
  { id: "Grace", gender: "female", age: "middle_aged", accent: "american",
    useCase: ["educational", "narration", "conversational"], style: ["calm", "soft", "neutral", "confident", "smooth"],
    description: "Unhurried American guide voice, quiet and sure of itself. Fits lessons, support scripts, and anything that should not startle the listener." },
  { id: "Owen", gender: "male", age: "young", accent: "australian",
    useCase: ["narration", "conversational", "social_media"], style: ["deep", "confident", "friendly"],
    description: "Dry Australian male register, low and unhurried. Documentary pacing with a hint of understatement." },
  { id: "Mina", gender: "female", age: "middle_aged", accent: "korean",
    useCase: ["narration"], style: ["calm", "soft"],
    description: "Quiet Korean female narration with a still, inward quality. Suits fiction, essays, and other long listens." },
  { id: "Kenji", gender: "male", age: "middle_aged", accent: "japanese",
    useCase: ["narration", "conversational"], style: ["calm", "friendly", "bright", "smooth", "soft"],
    description: "Measured Japanese male speech, polite without stiffness. Works for both straight narration and everyday dialogue." },
  { id: "Rafael", gender: "male", age: "middle_aged", accent: "spanish",
    useCase: ["narration", "educational", "entertainment", "social_media"], style: ["smooth", "neutral"],
    description: "A clear, composed male voice with a warm Spanish accent, balanced pacing, and a confident tone that feels approachable and precise." },
  { id: "Mateo", gender: "male", age: "young", accent: "spanish",
    useCase: ["entertainment", "narration"], style: ["soft", "friendly", "smooth", "calm"],
    description: "Young English with a light Spanish colour and an open, unguarded manner. Story-led reads that stay human rather than salesy." },
  { id: "Lucia", gender: "female", age: "middle_aged", accent: "spanish",
    useCase: ["educational"], style: ["confident", "soft", "bright"],
    description: "A clear, mature female voice with a natural Spanish accent, steady pacing, and a composed tone that feels warm, focused, and approachable." },
  { id: "Oliver", gender: "male", age: "middle_aged", accent: "british",
    useCase: ["narration"], style: ["formal", "soft", "calm", "neutral"],
    description: "British narrator with a quiet, careful manner and no hurry in him. Audiobooks and long voiceover that feel looked after." },
  { id: "Arthur", gender: "male", age: "old", accent: "british",
    useCase: ["narration"], style: ["deep", "expressive", "dramatic", "smooth", "breathy"],
    description: "Older British male with a worn, low register and a little gravel in the finish. Narration that feels lived-in rather than polished." },
  { id: "Isla", gender: "female", age: "young", accent: "british",
    useCase: ["narration", "social_media", "entertainment", "conversational"], style: ["friendly", "soft"],
    description: "A lively female voice with a bright British accent, clear delivery, and expressive energy that feels fresh, friendly, and naturally engaging." },
  { id: "Victoria", gender: "female", age: "middle_aged", accent: "british",
    useCase: ["educational", "narration", "conversational"], style: ["formal", "bright", "confident", "neutral", "calm"],
    description: "A poised female voice with a refined British accent, smooth pacing, and a lightly textured tone that feels elegant, confident, and composed." },
  { id: "Cooper", gender: "male", age: "middle_aged", accent: "australian",
    useCase: ["conversational", "social_media"], style: ["bright", "friendly", "expressive"],
    description: "A bold male voice with a strong Australian accent, relaxed pacing, and a casual tone that feels confident, rugged, and easygoing." },
  { id: "Mason", gender: "male", age: "middle_aged", accent: "australian",
    useCase: ["social_media", "narration"], style: ["calm", "smooth", "confident"],
    description: "Melbourne-casual male read, unhurried and smooth. Equally at home in a vlog or a long voiceover." },
  { id: "Ruby", gender: "female", age: "young", accent: "australian",
    useCase: ["conversational"], style: ["friendly", "neutral", "soft"],
    description: "A confident female voice with a natural Australian accent, lively pacing, and a warm tone that feels personable, sharp, and engaging." },
  { id: "Arjun", gender: "male", age: "middle_aged", accent: "indian",
    useCase: ["educational", "narration", "conversational"], style: ["friendly", "energetic", "bright", "expressive"],
    description: "Indian-English with a round, talkative timbre and plenty of lift. Explains and narrates without going stiff." },
  { id: "Rohan", gender: "male", age: "young", accent: "indian",
    useCase: ["social_media", "conversational"], style: ["confident", "energetic", "expressive", "friendly", "playful", "bright"],
    description: "Young Indian-English built for hooks and punchlines. Playful timing that wants a short, scroll-stopping clip." },
  { id: "Priya", gender: "female", age: "young", accent: "indian",
    useCase: ["conversational"], style: ["friendly", "bright", "smooth", "soft"],
    description: "A clear female voice with a natural Indian accent, warm pacing, and a composed tone that feels helpful, attentive, and easy to trust." },
  { id: "Bryce", gender: "male", age: "young", accent: "american",
    useCase: ["narration", "social_media", "educational", "conversational"], style: ["confident", "soft", "bright"],
    description: "Young American with a big, forward presence and a surprisingly light finish. Works for shorts, explainers, and story narration alike." },
  { id: "Trevor", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["narration", "entertainment", "social_media", "conversational"], style: ["confident", "energetic", "bright", "friendly"],
    description: "A casual male voice with a slightly gritty tone and a confident, unrehearsed style." },
  { id: "Evan", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["educational", "narration", "social_media"], style: ["confident", "calm", "deep", "formal"],
    description: "Formal American male with a low, even line. Turns lessons and documentaries into something you can actually stay with." },
  { id: "Nathan", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["narration"], style: ["deep", "soft", "neutral", "formal", "confident"],
    description: "Low American narration that barely raises its voice. Suits bedtime scripts, guided audio, and other slow, close listening." },
  { id: "Karan", gender: "male", age: "middle_aged", accent: "indian",
    useCase: ["narration", "educational", "social_media", "entertainment"], style: ["deep", "friendly", "soft", "expressive"],
    description: "A deep, friendly male voice with an Indian accent and a light, upbeat touch." },
  { id: "Wesley", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["narration", "educational", "entertainment"], style: ["deep", "confident", "raspy", "expressive", "calm"],
    description: "American baritone with a rasp at the edges and real storyteller weight. Holds ads, docs, and long fiction without thinning out." },
  { id: "Curtis", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["conversational"], style: ["deep", "confident", "dramatic"],
    description: "Broad American male voice, low and a little theatrical in conversation. Sits close to the mic and takes its time." },
  { id: "Miles", gender: "male", age: "middle_aged", accent: "british",
    useCase: ["narration", "entertainment"], style: ["calm", "smooth", "deep", "breathy"],
    description: "Late-night British baritone, breathy and unhurried. The kind of read that keeps headphones on." },
  { id: "Preston", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["entertainment", "social_media"], style: ["confident", "expressive", "friendly", "smooth", "calm"],
    description: "American commercial male who leans in on the key words. Friendly persuasion for spots and social ads." },
  { id: "Walter", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["educational", "narration"], style: ["deep", "smooth", "confident", "neutral", "energetic"],
    description: "American baritone with a straight-backed, well-meaning delivery. Suits instruction and sincere long-form reading." },
  { id: "Russell", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["narration", "entertainment"], style: ["raspy", "deep", "expressive"],
    description: "Gravel-voiced American narrator who sounds like he is telling you something private. Strong fit for close, characterful audiobooks." },
  { id: "Tunde", gender: "male", age: "young", accent: "african",
    useCase: ["social_media", "entertainment", "narration"], style: ["smooth", "calm", "friendly"],
    description: "Young african male voice, smooth and unhurried. Carries shorts, stories, and ads with an easy urban lilt." },
  { id: "Nigel", gender: "male", age: "middle_aged", accent: "british",
    useCase: ["conversational", "educational", "entertainment", "narration", "social_media"], style: ["bright", "confident", "friendly", "expressive", "energetic"],
    description: "Broadcast-ready British male with lift and colour in the phrasing. A generalist for ads, explainers, and on-camera energy." },
  { id: "Shane", gender: "male", age: "young", accent: "american",
    useCase: ["educational", "narration"], style: ["friendly", "calm", "soft"],
    description: "Soft-spoken young American, friendly and unhurried. A natural for explainers and classroom-style tracks." },
  { id: "Silas", gender: "male", age: "old", accent: "american",
    useCase: ["narration", "entertainment"], style: ["soft", "calm", "confident", "friendly"],
    description: "An older, deep male voice with a rugged Southern drawl and a wise, unhurried style." },
  { id: "Reid", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["conversational"], style: ["confident", "calm", "deep", "warm", "smooth"],
    description: "American agent voice: low, unhurried, and sure of the next sentence. Built for careful conversation rather than ads." },
  { id: "Emilio", gender: "male", age: "young", accent: "latin_american",
    useCase: ["entertainment", "social_media"], style: ["energetic", "friendly", "bright", "confident"],
    description: "Young Mexican Spanish with a grin in it. High spirits for clips, ads, and anything meant to feel like a good mood." },
  { id: "Alistair", gender: "male", age: "old", accent: "british",
    useCase: ["narration", "educational", "entertainment"], style: ["soft", "warm", "deep", "confident", "dramatic", "expressive"],
    description: "Elderly RP with a fireside hush and a storyteller's patience. Nature films, nostalgia, and kindly instruction all sit well." },
  { id: "Dominic", gender: "male", age: "young", accent: "american",
    useCase: ["conversational"], style: ["soft", "confident", "expressive"],
    description: "A deep male voice with a wide emotional range and a bold, dramatic delivery." },
  { id: "Emerson", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["educational", "narration"], style: ["warm", "smooth", "confident", "expressive"],
    description: "Polished American corporate read, smooth and a little ceremonial. Suits training decks and branded narration." },
  { id: "Harlan", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["narration", "educational"], style: ["confident", "energetic", "expressive"],
    description: "A polished American male narrator with clear, steady delivery for factual content." },
  { id: "Bennett", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["educational", "narration"], style: ["confident", "deep", "warm", "formal", "calm", "soft", "smooth", "raspy"],
    description: "Seasoned American instructor with a low, slightly worn timbre. Makes dense material feel walked-through rather than announced." },
  { id: "Elliot", gender: "male", age: "middle_aged", accent: "british",
    useCase: ["narration", "entertainment", "educational"], style: ["soft", "calm", "warm", "deep", "confident", "breathy"],
    description: "British male narration that barely leaves the chest. Slow, even, and close — built for long, gentle audiobooks." },
  { id: "Sebastian", gender: "male", age: "middle_aged", accent: "british",
    useCase: ["narration", "educational", "entertainment"], style: ["deep", "smooth", "calm", "soft"],
    description: "Low RP that stays close to the ear and never overplays the joke. Dark fiction, docs, and dry corporate reads all work." },
  { id: "Haruto", gender: "male", age: "young", accent: "japanese",
    useCase: ["entertainment", "narration"], style: ["friendly", "smooth", "energetic", "bright"],
    description: "Young Japanese male with a bright, friendly line and no extra ornament. Suits narration, spots, and light entertainment." },
  { id: "Freddie", gender: "male", age: "young", accent: "british",
    useCase: ["social_media", "narration", "educational", "entertainment"], style: ["deep", "friendly", "smooth", "calm"],
    description: "Young British male, deeper than expected and easy to like. Shorts, ads, and coming-of-age narration all sit naturally." },
  { id: "Logan", gender: "male", age: "middle_aged", accent: "american",
    useCase: ["narration", "conversational", "educational"], style: ["confident", "calm", "friendly", "soft", "expressive"],
    description: "American voice that sounds already mid-conversation. Easy authority for shows, lessons, and honest ads." },
  { id: "Poppy", gender: "female", age: "young", accent: "british",
    useCase: ["conversational", "narration"], style: ["energetic", "soft", "confident", "bright", "friendly"],
    description: "Fresh British female voice that talks rather than announces. Bright enough for stories, casual enough for chat." },
  { id: "Harper", gender: "female", age: "young", accent: "american",
    useCase: ["social_media", "entertainment", "conversational"], style: ["bright", "energetic"],
    description: "A relaxed female voice with natural pauses and a casual, unscripted delivery." },
  { id: "Cordelia", gender: "female", age: "middle_aged", accent: "american",
    useCase: ["narration", "entertainment"], style: ["calm", "deep", "warm", "smooth", "soft"],
    description: "A calm, polished female character voice with an elegant but menacing edge." },
  { id: "Reese", gender: "female", age: "young", accent: "american",
    useCase: ["entertainment"], style: ["confident", "energetic", "smooth", "soft", "expressive"],
    description: "A young female voice with confident energy and a bold, determined delivery." },
  { id: "Hazel", gender: "female", age: "young", accent: "american",
    useCase: ["conversational"], style: ["warm", "smooth"],
    description: "Low-key American conversation, smooth and unforced. Chats, explainers, and editorial audio that should not sound staged." },
  { id: "Juliet", gender: "female", age: "young", accent: "american",
    useCase: ["narration"], style: ["calm", "soft", "warm", "smooth"],
    description: "Slow American female narration with a hush to it. Audiobooks, guided scripts, and other close, unhurried listening." },
  { id: "Piper", gender: "female", age: "young", accent: "american",
    useCase: ["conversational"], style: ["energetic", "soft"],
    description: "A cheerful female voice with upbeat energy and a bright, lively delivery." },
  { id: "Reyna", gender: "female", age: "middle_aged", accent: "southeast_asian",
    useCase: ["educational", "narration"], style: ["energetic", "smooth", "soft"],
    description: "Filipino character-actress energy: big, warm, and ready to switch roles mid-script. Lessons and narration with real stage presence." },
  { id: "Kayla", gender: "female", age: "young", accent: "american",
    useCase: ["social_media", "conversational"], style: ["energetic", "confident", "bright"],
    description: "A natural Gen Z female voice with a casual, low-key, and unpolished style." },
  { id: "Sloane", gender: "female", age: "young", accent: "american",
    useCase: ["narration"], style: ["bright", "confident", "energetic", "expressive"],
    description: "Young American storyteller who stays sharp over long stretches. Enough colour in the line to keep a chapter from going flat." },
  { id: "Iris", gender: "female", age: "young", accent: "american",
    useCase: ["conversational"], style: ["friendly", "soft", "smooth", "warm"],
    description: "A clear, patient female voice with a gentle and reassuring tone." },
  { id: "Freya", gender: "female", age: "young", accent: "british",
    useCase: ["conversational", "educational", "social_media"], style: ["friendly", "bright", "energetic", "confident"],
    description: "A clear, bright British female voice with a neutral and easy-to-follow delivery." },
  { id: "Brooke", gender: "female", age: "middle_aged", accent: "american",
    useCase: ["conversational", "entertainment", "social_media"], style: ["friendly", "confident", "soft"],
    description: "American female who sounds like she walked in already talking. Bright, unfussy conversation, not a booth read." },
  { id: "Bonnie", gender: "female", age: "middle_aged", accent: "australian",
    useCase: ["narration"], style: ["confident", "soft", "warm", "smooth", "calm"],
    description: "Quiet Australian female narration, sure of itself without raising volume. Story-led audio that stays still." },
  { id: "Imogen", gender: "female", age: "young", accent: "british",
    useCase: ["educational", "narration", "conversational"], style: ["bright", "confident", "energetic", "expressive", "friendly"],
    description: "Young British explainer voice, bright and unpretentious. Training films and narration that sound like a real person, not a booth." },
  { id: "Arabella", gender: "female", age: "middle_aged", accent: "british",
    useCase: ["narration", "conversational"], style: ["calm", "soft", "breathy"],
    description: "Breath-led British female voice, quiet and expensive-sounding. Conversation and narration that stay close to the mic." },
  { id: "Colleen", gender: "female", age: "middle_aged", accent: "american",
    useCase: ["narration", "educational"], style: ["friendly", "confident", "warm", "deep", "calm", "soft", "smooth"],
    description: "A warm, clear female voice that moves naturally between storytelling and instruction." },
  { id: "Margo", gender: "female", age: "young", accent: "american",
    useCase: ["entertainment", "social_media", "conversational"], style: ["playful", "friendly", "bright", "neutral"],
    description: "A dry female voice with flat delivery and sharp, understated sarcasm." },
  { id: "Nora", gender: "female", age: "young", accent: "american",
    useCase: ["conversational", "educational", "narration"], style: ["friendly", "bright", "calm", "smooth"],
    description: "A young female voice with a casual, chatty style and an inquisitive tone." },
  { id: "Bianca", gender: "female", age: "middle_aged", accent: "brazilian",
    useCase: ["conversational"], style: ["bright", "smooth", "calm", "neutral"],
    description: "A serious female voice with a Brazilian accent and crisp, deliberate delivery." },
  { id: "Sari", gender: "female", age: "middle_aged", accent: "southeast_asian",
    useCase: ["educational"], style: ["soft", "friendly", "bright", "energetic", "confident"],
    description: "Clear Indonesian female instructor, bright and well projected. Built for lessons and other information that has to land first time." },
  { id: "Kabir", gender: "male", age: "young", accent: "indian",
    useCase: ["social_media", "entertainment"], style: ["energetic", "expressive", "friendly", "warm", "smooth", "confident"],
    description: "An energetic young male Hindi voice with a punchy, expressive style made for short-form video." },
  { id: "Kavya", gender: "female", age: "young", accent: "indian",
    useCase: ["conversational", "social_media", "narration", "educational"], style: ["friendly", "soft", "bright"],
    description: "Soft Hindi with a light, companionable lift. Easy to sit with across stories, chats, and learning clips." },
  { id: "Aarav", gender: "male", age: "young", accent: "indian",
    useCase: ["conversational", "educational", "narration"], style: ["deep", "smooth", "calm", "confident", "formal"],
    description: "Young Hindi with a low, composed line and service-desk manners. Formal enough for support, clear enough for lessons." },
  { id: "Dev", gender: "male", age: "young", accent: "indian",
    useCase: ["conversational"], style: ["friendly", "smooth", "soft", "calm"],
    description: "A natural, conversational male voice with an Indian accent, easygoing and well suited to AI agents." },
  { id: "Nikhil", gender: "male", age: "young", accent: "indian",
    useCase: ["narration", "educational", "social_media"], style: ["energetic", "bright", "expressive", "confident", "friendly"],
    description: "A clear, confident male Hindi voice with youthful energy and a strong narrator's delivery." },
  { id: "Ashok", gender: "male", age: "middle_aged", accent: "indian",
    useCase: ["narration", "social_media", "educational"], style: ["expressive", "smooth", "soft", "calm"],
    description: "A mature, expressive male voice with an Indian accent and a confident storytelling presence." },
  { id: "Ishita", gender: "female", age: "young", accent: "indian",
    useCase: ["narration"], style: ["expressive", "friendly", "soft", "warm", "smooth", "bright", "energetic"],
    description: "A soft, cheerful female Hindi voice with lively modulation and expressive warmth." },
  { id: "Aman", gender: "male", age: "young", accent: "indian",
    useCase: ["social_media", "narration"], style: ["soft", "expressive", "calm", "smooth", "warm"],
    description: "Young Hindi that keeps the volume down and the feeling up. Shorts and story tracks with a tender, unforced line." },
  { id: "Shalini", gender: "female", age: "middle_aged", accent: "indian",
    useCase: ["narration"], style: ["confident", "bright", "energetic", "expressive", "friendly"],
    description: "A precise, authoritative female Hindi voice with a well-paced, news-anchor delivery." },
  { id: "Manav", gender: "male", age: "young", accent: "indian",
    useCase: ["narration", "educational"], style: ["expressive", "smooth", "calm"],
    description: "A steady, articulate male Hindi voice that explains things clearly and calmly." },
  { id: "Nisha", gender: "female", age: "young", accent: "indian",
    useCase: ["conversational"], style: ["friendly", "warm", "expressive", "energetic", "bright"],
    description: "A smooth, empathetic female Hindi voice with a warm, professional manner." },
  { id: "Karthik", gender: "male", age: "young", accent: "indian",
    useCase: ["conversational", "educational", "social_media"], style: ["energetic", "friendly"],
    description: "Young Tamil with a bounce, as if the conversation already started. Chats, lessons, and social clips without the formal varnish." },
  { id: "Meena", gender: "female", age: "middle_aged", accent: "indian",
    useCase: ["conversational"], style: ["friendly", "bright", "soft", "energetic"],
    description: "Tamil customer-care colour: bright, kind, and never clipped. Makes a help-line script sound like a person." },
  { id: "Vani", gender: "female", age: "middle_aged", accent: "indian",
    useCase: ["conversational"], style: ["bright", "energetic", "playful"],
    description: "Bright Tamil with a teasing lift, still easy to follow on a call. Energy without losing the help-desk job." },
  { id: "Surya", gender: "male", age: "young", accent: "indian",
    useCase: ["social_media", "educational"], style: ["energetic", "bright", "confident"],
    description: "Young Tamil that snaps along, sure of every beat. Explainers, lessons, and social cuts that need forward motion." },
  { id: "Deepa", gender: "female", age: "middle_aged", accent: "indian",
    useCase: ["narration", "educational"], style: ["friendly", "soft", "bright", "confident"],
    description: "A melodic, soothing female Tamil voice with a calm, poetic flow." },
  { id: "Sundar", gender: "male", age: "middle_aged", accent: "indian",
    useCase: ["narration", "educational"], style: ["friendly", "smooth", "deep", "calm", "breathy"],
    description: "Deep Tamil narration with a breathy, unhurried finish. Stories and lessons that sound invited-in rather than presented." },
  { id: "Gurpreet", gender: "male", age: "young", accent: "indian",
    useCase: ["conversational"], style: ["calm", "smooth", "soft"],
    description: "Young Punjabi with a low, well-mannered line. Regional support audio that stays smooth and unhurried." },
  { id: "Madhura", gender: "female", age: "young", accent: "indian",
    useCase: ["conversational", "social_media"], style: ["bright", "energetic", "friendly"],
    description: "Young Marathi with a bright, outgoing manner on the line. Support scripts and social audio that feel immediately familiar." },
  { id: "Venkat", gender: "male", age: "middle_aged", accent: "indian",
    useCase: ["narration"], style: ["dramatic", "confident", "expressive", "warm", "smooth"],
    description: "Telugu narrator who plays every turn for keeps. Smooth heat and real character colour for long fiction." },
  { id: "Rajan", gender: "male", age: "middle_aged", accent: "indian",
    useCase: ["narration", "conversational"], style: ["expressive", "smooth", "energetic"],
    description: "Tamil with a rolling, musical line and plenty of movement. Audiobooks and talk tracks that never sit flat." },
  { id: "Lekha", gender: "female", age: "middle_aged", accent: "indian",
    useCase: ["narration"], style: ["expressive", "friendly", "bright"],
    description: "Malayalam storytelling with a bright, companionable colour. Fiction that feels told across a table, not from a booth." },
  { id: "Sneha", gender: "female", age: "young", accent: "indian",
    useCase: ["entertainment", "narration"], style: ["energetic", "friendly"],
    description: "A bright, energetic female Kannada voice with a lively radio-host style." },
  { id: "Bhavana", gender: "female", age: "middle_aged", accent: "indian",
    useCase: ["conversational"], style: ["friendly", "bright", "energetic"],
    description: "A calm, empathetic female Kannada voice with clear and patient delivery." },
  { id: "Mohan", gender: "male", age: "middle_aged", accent: "indian",
    useCase: ["conversational"], style: ["calm", "bright"],
    description: "Kannada conversation with a settled, daylight tone. Companion and chat audio that does not press." },
  { id: "Divya", gender: "female", age: "young", accent: "indian",
    useCase: ["conversational"], style: ["calm", "friendly", "bright"],
    description: "A friendly, attentive female Tamil voice with a natural conversational rhythm." },
  { id: "Camila", gender: "female", age: "young", accent: "latin_american",
    useCase: ["conversational", "narration"], style: ["energetic", "friendly", "bright", "breathy"],
    description: "A lively young female Spanish voice with a bright, airy tone and an easy conversational flow." },
  { id: "Santiago", gender: "male", age: "middle_aged", accent: "latin_american",
    useCase: ["narration"], style: ["confident", "deep", "warm", "soft"],
    description: "A deep, resonant male Spanish voice with a soft edge and an intimate, reassuring delivery." },
  { id: "Damian", gender: "male", age: "middle_aged", accent: "latin_american",
    useCase: ["narration", "conversational"], style: ["confident", "energetic"],
    description: "A relaxed adult male Spanish voice with an even, unhurried delivery and quiet confidence." },
  { id: "Facundo", gender: "male", age: "middle_aged", accent: "latin_american",
    useCase: ["conversational", "narration"], style: ["calm", "friendly", "warm", "breathy", "expressive"],
    description: "A leisurely Argentine male voice, warm and softly spoken, landing somewhere between chatting and reading aloud." },
  { id: "Valentina", gender: "female", age: "young", accent: "latin_american",
    useCase: ["narration", "conversational"], style: ["calm", "friendly", "soft", "warm", "neutral"],
    description: "A hushed young female Spanish voice, soft to the point of a murmur, for calm and intimate reads." },
  { id: "Alonso", gender: "male", age: "middle_aged", accent: "latin_american",
    useCase: ["narration", "conversational"], style: ["friendly", "neutral"],
    description: "A mid-range male Spanish voice with clear diction and an easy charm that adapts to almost any script." },
  { id: "Renata", gender: "female", age: "young", accent: "latin_american",
    useCase: ["social_media", "entertainment"], style: ["energetic", "expressive", "bright"],
    description: "A high-energy young female Spanish voice with an insistent, up-tempo push behind every line." },
  { id: "Mariana", gender: "female", age: "young", accent: "latin_american",
    useCase: ["social_media", "conversational"], style: ["confident", "friendly", "warm", "neutral"],
    description: "A radiant young Colombian female voice with a musical rise and fall and easy confidence." },
  { id: "Lorenzo", gender: "male", age: "middle_aged", accent: "latin_american",
    useCase: ["narration"], style: ["formal", "calm", "deep", "dramatic", "warm"],
    description: "A dark, formal male Spanish voice that holds its weight steady through long, sombre passages." },
  { id: "Emiliano", gender: "male", age: "middle_aged", accent: "latin_american",
    useCase: ["narration", "social_media", "entertainment"], style: ["deep", "warm", "breathy", "dramatic", "expressive"],
    description: "A deep male Spanish voice with a breath-heavy, confiding delivery that carries real emotional weight." },
  { id: "Paulina", gender: "female", age: "young", accent: "latin_american",
    useCase: ["conversational", "narration", "social_media"], style: ["calm", "friendly", "warm", "neutral"],
    description: "A slow-moving female Spanish voice with a plain, sincere tone that never oversells the copy." },
  { id: "Alvaro", gender: "male", age: "middle_aged", accent: "spanish",
    useCase: ["narration", "social_media", "entertainment"], style: ["soft", "raspy", "expressive", "dramatic", "deep"],
    description: "A gentle, slightly gravelly Castilian male voice with a low, expressive register for narration." },
  { id: "Rodrigo", gender: "male", age: "middle_aged", accent: "spanish",
    useCase: ["entertainment"], style: ["confident", "dramatic", "expressive", "bright"],
    description: "A male Spanish voice at full throat, unrestrained and blazing, for scenes of fury and confrontation." },
  { id: "Guillermo", gender: "male", age: "middle_aged", accent: "spanish",
    useCase: ["narration", "educational"], style: ["calm", "deep", "expressive", "warm", "formal", "confident"],
    description: "A rich Castilian male voice with weight and warmth, suited to long-form literary narration." },
  { id: "Marta", gender: "female", age: "middle_aged", accent: "spanish",
    useCase: ["narration", "conversational"], style: ["formal", "friendly", "smooth", "neutral"],
    description: "A collected female Spanish voice with a faint Galician lilt and an even, well-mannered read." },
  { id: "Sergio", gender: "male", age: "middle_aged", accent: "spanish",
    useCase: ["conversational", "social_media"], style: ["friendly", "warm", "calm", "soft"],
    description: "A relaxed Castilian male voice with a loose, off-the-cuff rhythm that fits everyday dialogue." },
  { id: "Hector", gender: "male", age: "young", accent: "spanish",
    useCase: ["entertainment", "narration"], style: ["breathy"],
    description: "An airy young Castilian male voice with a serene, breath-forward delivery for character work and narration." },
  { id: "Javier", gender: "male", age: "middle_aged", accent: "spanish",
    useCase: ["narration", "conversational", "entertainment"], style: ["confident", "expressive", "friendly", "warm", "soft"],
    description: "Castilian male who can turn a page or a conversation without changing personality. Soft confidence for stories and dialogue alike." },
  { id: "Carmen", gender: "female", age: "middle_aged", accent: "spanish",
    useCase: ["conversational"], style: ["confident", "soft", "warm", "smooth", "playful"],
    description: "A softly spoken female voice with a Spanish accent, worldly and articulate, with a light playful edge." },
  { id: "Thiago", gender: "male", age: "middle_aged", accent: "brazilian",
    useCase: ["educational", "narration"], style: ["friendly", "neutral", "soft"],
    description: "Brazilian Portuguese with a mild, good-humoured evenness. Lessons and narration that stay pleasant without performing excitement." },
  { id: "Juliana", gender: "female", age: "middle_aged", accent: "brazilian",
    useCase: ["educational", "social_media"], style: ["calm", "neutral"],
    description: "An easygoing Brazilian female voice with a level, patient read that suits walkthroughs and chat." },
  { id: "Larissa", gender: "female", age: "young", accent: "brazilian",
    useCase: ["narration", "conversational"], style: ["friendly", "expressive", "smooth", "calm"],
    description: "Young Brazilian Portuguese that glides rather than punches. Friendly, even phrasing for stories and everyday talk." },
  { id: "Vinicius", gender: "male", age: "middle_aged", accent: "brazilian",
    useCase: ["narration", "educational", "conversational"], style: ["formal", "smooth", "neutral"],
    description: "A measured Brazilian male voice with an unadorned, level read that carries dense material without strain." },
  { id: "Bruna", gender: "female", age: "young", accent: "brazilian",
    useCase: ["social_media", "conversational"], style: ["friendly", "bright"],
    description: "A quick, bright young Brazilian female voice with an interior-state twang and natural sales instinct." },
  { id: "Leandro", gender: "male", age: "middle_aged", accent: "brazilian",
    useCase: ["educational"], style: ["confident", "neutral", "formal", "smooth"],
    description: "An even-keeled Brazilian male voice with newsroom composure, ideal for reports and explainer scripts." },
  { id: "Diogo", gender: "male", age: "young", accent: "portuguese",
    useCase: ["conversational"], style: ["friendly", "calm"],
    description: "Young male English with a Portuguese colour and nowhere to be. Quiet, friendly chat rather than a presentation." },
  { id: "Rui", gender: "male", age: "middle_aged", accent: "portuguese",
    useCase: ["conversational"], style: ["friendly", "deep", "neutral", "calm", "breathy"],
    description: "A deep, laid-back European Portuguese male voice with a soft, breathy edge and a plain, friendly manner." },
  { id: "Nuno", gender: "male", age: "old", accent: "portuguese",
    useCase: ["entertainment", "educational", "narration"], style: ["neutral", "calm", "soft", "friendly"],
    description: "A settled male voice from Portugal with an unvarying, uncolored tone that holds up over hours of audio." },
  { id: "Bernardo", gender: "male", age: "young", accent: "portuguese",
    useCase: ["entertainment"], style: ["confident", "calm"],
    description: "A steady young male voice with a Portuguese accent that makes dense, technical topics sound effortless." },
  { id: "Matilde", gender: "female", age: "young", accent: "portuguese",
    useCase: ["educational", "social_media"], style: ["formal", "calm"],
    description: "A self-possessed young female voice with a faint Portuguese accent and a formal, deliberate delivery." },
  { id: "Duarte", gender: "male", age: "middle_aged", accent: "portuguese",
    useCase: ["narration"], style: ["confident", "smooth", "neutral", "soft"],
    description: "A dark, even male voice with a trace of Portuguese accent, steady and serious enough to carry feature-length narration." },
  { id: "Julien", gender: "male", age: "middle_aged", accent: "french",
    useCase: ["conversational"], style: ["friendly", "energetic", "expressive", "bright"],
    description: "A bright French male voice, warm and quick in conversation, with an unforced everyday manner." },
  { id: "Genevieve", gender: "female", age: "middle_aged", accent: "french",
    useCase: ["educational", "social_media"], style: ["calm", "friendly", "warm"],
    description: "A homegrown Quebec French female voice with a patient, welcoming tone that suits lessons and how-to content." },
  { id: "Olivier", gender: "male", age: "middle_aged", accent: "french",
    useCase: ["narration"], style: ["calm", "soft", "warm", "neutral"],
    description: "A whisper-soft French male voice, warm and near-motionless, for listening late at night." },
  { id: "Antoine", gender: "male", age: "middle_aged", accent: "french",
    useCase: ["narration"], style: ["calm", "deep"],
    description: "A low, tranquil French-Canadian male voice that leaves space between thoughts." },
  { id: "Elodie", gender: "female", age: "young", accent: "french",
    useCase: ["narration", "educational"], style: ["friendly", "bright"],
    description: "Young French with a bright, forward diction and no lag. Lessons and media reads that stay alert." },
  { id: "Camille", gender: "female", age: "middle_aged", accent: "french",
    useCase: ["narration", "educational", "entertainment"], style: ["confident", "expressive", "bright"],
    description: "A rich, emotive French female voice with a magnetic read that carries long-form fiction and narration." },
  { id: "Manon", gender: "female", age: "middle_aged", accent: "french",
    useCase: ["conversational", "narration"], style: ["expressive", "calm", "playful", "smooth"],
    description: "A supple Parisian female voice with playful shading that moves easily between chat and performance." },
  { id: "Mathieu", gender: "male", age: "middle_aged", accent: "french",
    useCase: ["narration", "entertainment"], style: ["friendly", "calm"],
    description: "A friendly, level French male voice with an unforced read that works across long and short formats." },
  { id: "Celine", gender: "female", age: "middle_aged", accent: "french",
    useCase: ["educational", "entertainment"], style: ["formal", "energetic", "bright"],
    description: "A polished, upbeat French female voice with precise articulation and quiet authority behind every line." },
  { id: "Baptiste", gender: "male", age: "middle_aged", accent: "french",
    useCase: ["narration", "educational"], style: ["calm", "smooth"],
    description: "A smooth French male voice with a calm, even cadence that carries long passages effortlessly." },
  { id: "Noemie", gender: "female", age: "middle_aged", accent: "french",
    useCase: ["entertainment"], style: ["expressive", "bright", "energetic"],
    description: "A high-shine French female voice with quick, punchy attack for short advertising spots." },
  { id: "Jonas", gender: "male", age: "middle_aged", accent: "german",
    useCase: ["conversational", "educational", "entertainment", "narration"], style: ["neutral", "warm", "breathy", "soft"],
    description: "An even-tempered German male voice with a soft, breath-light finish that holds up across extended dialogue." },
  { id: "Konrad", gender: "male", age: "middle_aged", accent: "german",
    useCase: ["narration"], style: ["bright", "raspy", "breathy", "calm"],
    description: "A tender German male voice with a soft, lulling manner made for reading to children." },
  { id: "Matthias", gender: "male", age: "middle_aged", accent: "german",
    useCase: ["educational", "entertainment"], style: ["confident", "expressive", "formal", "energetic"],
    description: "A forceful German male voice with clipped, driving phrasing that cuts straight through a busy broadcast." },
  { id: "Florian", gender: "male", age: "middle_aged", accent: "german",
    useCase: ["educational", "narration", "social_media"], style: ["formal", "confident", "soft", "calm"],
    description: "A courteous German male voice with a measured, docent-like manner and no trace of hurry." },
  { id: "Annika", gender: "female", age: "middle_aged", accent: "german",
    useCase: ["conversational", "educational"], style: ["friendly", "confident", "soft"],
    description: "A soft-spoken German female voice with an assured, patient manner suited to lessons and assistant dialogue." },
  { id: "Tobias", gender: "male", age: "middle_aged", accent: "german",
    useCase: ["conversational", "educational"], style: ["confident", "warm", "soft", "neutral", "friendly"],
    description: "A reassuring German male voice with an easy professional polish, well matched to support lines and training material." },
  { id: "Lena", gender: "female", age: "young", accent: "german",
    useCase: ["social_media", "conversational"], style: ["energetic", "bright", "friendly"],
    description: "A fast, bright young German female voice with a newsroom edge that never turns stiff." },
  { id: "Reinhard", gender: "male", age: "old", accent: "german",
    useCase: ["narration", "entertainment"], style: ["deep", "dramatic", "raspy"],
    description: "An aged German male voice, low and roughened, with the theatrical weight a dark story needs." },
  { id: "Stefan", gender: "male", age: "middle_aged", accent: "german",
    useCase: ["conversational", "entertainment"], style: ["energetic", "friendly", "playful", "expressive", "bright"],
    description: "A buoyant German male voice with on-air timing and a mischievous streak that keeps banter moving." },
  { id: "Marlene", gender: "female", age: "middle_aged", accent: "german",
    useCase: ["narration", "entertainment"], style: ["calm", "smooth", "soft", "neutral"],
    description: "A serene German female voice with quiet authority and understated feeling, at home in nature documentaries." },
  { id: "Marco", gender: "male", age: "young", accent: "italian",
    useCase: ["social_media"], style: ["friendly", "energetic", "expressive", "soft"],
    description: "A young Italian male voice with an upbeat grin behind it, tuned for short social clips." },
  { id: "Giulia", gender: "female", age: "young", accent: "italian",
    useCase: ["narration", "entertainment"], style: ["soft", "energetic"],
    description: "A young Italian female voice with a bubbly lift and an eager, forward energy." },
  { id: "Riccardo", gender: "male", age: "middle_aged", accent: "italian",
    useCase: ["narration", "educational"], style: ["formal", "soft", "neutral"],
    description: "An even, unshowy Italian male voice with a soft register built for straightforward narration." },
  { id: "Valeria", gender: "female", age: "middle_aged", accent: "italian",
    useCase: ["entertainment", "social_media", "educational"], style: ["energetic", "expressive", "confident", "bright"],
    description: "A high-voltage Italian female voice with a persuasive snap that carries marketing copy." },
  { id: "Massimo", gender: "male", age: "middle_aged", accent: "italian",
    useCase: ["narration", "educational"], style: ["confident", "calm", "soft", "neutral"],
    description: "A seasoned Italian male voice with measured calm and steady control, at home in long audiobooks." },
  { id: "Alessandro", gender: "male", age: "middle_aged", accent: "italian",
    useCase: ["narration"], style: ["energetic", "expressive", "confident", "bright"],
    description: "A vivid Italian male voice with strong colour and conviction that keeps a long narrative alive." },
  { id: "Davide", gender: "male", age: "middle_aged", accent: "italian",
    useCase: ["entertainment", "narration", "social_media"], style: ["formal", "bright", "energetic", "friendly", "expressive"],
    description: "A stage-trained Italian male voice with bright projection and a relentless forward drive." },
  { id: "Giulio", gender: "male", age: "young", accent: "italian",
    useCase: ["educational"], style: ["formal", "warm", "energetic", "expressive"],
    description: "A credible young Italian male voice with professional polish and flexible, warm delivery." },
  { id: "Taras", gender: "male", age: "middle_aged", accent: "slavic",
    useCase: ["educational"], style: ["confident", "smooth", "formal"],
    description: "A steady Ukrainian male voice with formal composure and deliberate pauses that make dense material land." },
  { id: "Andrei", gender: "male", age: "middle_aged", accent: "slavic",
    useCase: ["social_media", "entertainment", "narration", "conversational"], style: ["calm", "neutral"],
    description: "A neutral Russian male voice with an unmarked, general-purpose read and no strong colour of its own." },
  { id: "Yana", gender: "female", age: "middle_aged", accent: "slavic",
    useCase: ["entertainment", "conversational", "social_media"], style: ["smooth", "bright", "calm"],
    description: "Bulgarian female voice that can go news, ads, or fiction without changing personality. Smooth, unruffled, lightly commercial." },
  { id: "Bohdan", gender: "male", age: "middle_aged", accent: "slavic",
    useCase: ["conversational", "educational"], style: ["friendly", "calm", "confident", "smooth", "soft"],
    description: "A warm Ukrainian male voice, low and composed, that settles into long conversation comfortably." },
  { id: "Vadim", gender: "male", age: "middle_aged", accent: "slavic",
    useCase: ["narration", "entertainment", "social_media"], style: ["deep", "bright", "friendly", "warm", "raspy", "calm"],
    description: "A low Russian male voice with a slight gravel edge, bright and good-humoured without losing its steadiness." },
  { id: "Kirill", gender: "male", age: "middle_aged", accent: "slavic",
    useCase: ["narration", "educational"], style: ["calm", "neutral", "soft"],
    description: "An unhurried Russian male voice with even tempo and restrained colour, built for hours of continuous reading." },
  { id: "Marek", gender: "male", age: "middle_aged", accent: "slavic",
    useCase: ["narration"], style: ["friendly", "bright", "soft", "warm"],
    description: "Polish narrator with a light, companionable colour and no bardic thunder. Novels and guides that feel walked through." },
  { id: "Szymon", gender: "male", age: "middle_aged", accent: "slavic",
    useCase: ["narration", "entertainment"], style: ["deep", "breathy", "calm"],
    description: "A deep Polish male voice with a hushed, ominous undertow made for tension and dread." },
  { id: "Faisal", gender: "male", age: "middle_aged", accent: "arabic",
    useCase: ["entertainment", "social_media", "conversational"], style: ["friendly", "soft", "calm", "smooth"],
    description: "Arabic male voice, low and easy in the phrase, never barked. Conversation, spots, and social audio with a soft finish." },
  { id: "Layla", gender: "female", age: "young", accent: "arabic",
    useCase: ["conversational", "entertainment"], style: ["friendly", "warm", "soft", "calm", "neutral"],
    description: "Young Arabic with an easy, neighbourly manner and no hard sell. Soft enough for chat, clear enough for spots." },
  { id: "Hind", gender: "female", age: "middle_aged", accent: "arabic",
    useCase: ["entertainment", "conversational", "social_media"], style: ["energetic", "friendly", "bright"],
    description: "A spirited Moroccan Arabic female voice with a bright, coaxing lift that sells without pushing." },
  { id: "Rania", gender: "female", age: "middle_aged", accent: "arabic",
    useCase: ["narration", "entertainment"], style: ["smooth", "soft", "neutral"],
    description: "A smooth Modern Standard Arabic female voice with soft edges and a relaxed, neutral read." },
  { id: "Yousef", gender: "male", age: "young", accent: "arabic",
    useCase: ["narration", "educational", "social_media"], style: ["calm", "soft"],
    description: "A young Saudi male voice with fine pitch control and a hushed seriousness that suits long reads." },
  { id: "Karim", gender: "male", age: "middle_aged", accent: "arabic",
    useCase: ["narration", "social_media", "entertainment"], style: ["dramatic", "friendly", "expressive", "bright"],
    description: "A warm Egyptian Arabic male voice with theatrical colour and a flair for character work." },
  { id: "Wei", gender: "male", age: "young", accent: "chinese",
    useCase: ["narration", "educational"], style: ["neutral", "calm", "friendly", "soft"],
    description: "Young Mandarin male with a plain, contemporary line and no extra drama. Docs, lessons, and corporate tracks that should stay approachable." },
  { id: "Meilin", gender: "female", age: "middle_aged", accent: "chinese",
    useCase: ["educational", "conversational"], style: ["energetic", "bright"],
    description: "An animated female voice, Chinese-accented and quick on its feet, well suited to explainers and training material." },
  { id: "Haoran", gender: "male", age: "young", accent: "chinese",
    useCase: ["narration", "conversational"], style: ["calm", "smooth", "neutral"],
    description: "A smooth young Mandarin male voice with textbook enunciation and a placid, even keel." },
  { id: "Zihan", gender: "male", age: "young", accent: "chinese",
    useCase: ["narration", "conversational", "entertainment"], style: ["friendly", "calm"],
    description: "An agreeable Mandarin male voice with an uncluttered tone and a soft-spoken manner for everyday content." },
  { id: "Aoi", gender: "female", age: "middle_aged", accent: "japanese",
    useCase: ["conversational", "social_media"], style: ["confident", "smooth", "bright"],
    description: "A bright Japanese female voice with unforced phrasing and a chatty ease that never sounds staged." },
  { id: "Yuki", gender: "female", age: "middle_aged", accent: "japanese",
    useCase: ["narration", "educational"], style: ["calm", "soft"],
    description: "A quiet Japanese female voice with immaculate enunciation and a steady, unshowy cadence." },
  { id: "Sota", gender: "male", age: "young", accent: "japanese",
    useCase: ["conversational"], style: ["calm", "smooth", "neutral"],
    description: "Young Japanese male who never rushes a reply. Dialogue that sounds settled, not performed." },
  { id: "Riku", gender: "male", age: "young", accent: "japanese",
    useCase: ["narration"], style: ["deep", "soft"],
    description: "A deep, feather-soft Japanese male voice that slows the pulse and settles a room." },
  { id: "Hikari", gender: "female", age: "middle_aged", accent: "japanese",
    useCase: ["narration"], style: ["calm", "smooth", "warm", "deep"],
    description: "A low, smooth Japanese female voice with slow-burning warmth and a composed, literary bearing." },
  { id: "Nanami", gender: "female", age: "middle_aged", accent: "japanese",
    useCase: ["entertainment", "educational"], style: ["energetic", "bright"],
    description: "A lucid Japanese female voice with exceptional intelligibility, made for public announcements and step-by-step instruction." },
  { id: "Yuto", gender: "male", age: "young", accent: "japanese",
    useCase: ["narration", "conversational", "social_media"], style: ["smooth", "soft"],
    description: "A silky, low-key Japanese male voice with a hushed quality that suits quiet listening and short-form audio." },
  { id: "Sakura", gender: "female", age: "middle_aged", accent: "japanese",
    useCase: ["narration", "educational"], style: ["calm", "soft", "warm"],
    description: "A gentle Japanese female voice with dependable warmth and an easy register that never tires the ear." },
  { id: "Rina", gender: "female", age: "young", accent: "japanese",
    useCase: ["conversational", "entertainment", "narration"], style: ["bright", "playful", "friendly"],
    description: "A bright young Japanese female voice with a light, playful lift and diction sharp enough to follow first time." },
  { id: "Jihoon", gender: "male", age: "middle_aged", accent: "korean",
    useCase: ["narration", "conversational"], style: ["formal", "calm", "soft", "warm", "neutral"],
    description: "A trained Korean male voice with musical phrasing and sensitive delivery for literary and reflective material." },
  { id: "Minjun", gender: "male", age: "middle_aged", accent: "korean",
    useCase: ["conversational"], style: ["calm", "soft", "neutral"],
    description: "A low, comfortable Korean male voice with an unforced, settled delivery." },
  { id: "Seojun", gender: "male", age: "middle_aged", accent: "korean",
    useCase: ["conversational"], style: ["bright", "friendly"],
    description: "An easy, level Korean male voice with a matter-of-fact tone that works well for reviews and walkthroughs." },
  { id: "Daeho", gender: "male", age: "old", accent: "korean",
    useCase: ["entertainment", "social_media", "narration"], style: ["calm", "raspy", "expressive"],
    description: "A gravelled Korean male voice with a rough, unpolished edge and plenty of age in it." },
  { id: "Jiwoo", gender: "female", age: "middle_aged", accent: "korean",
    useCase: ["social_media", "entertainment", "conversational"], style: ["friendly", "bright"],
    description: "A sunny Korean female voice with crisp, chirpy delivery that cuts through background noise." },
  { id: "Hyunwoo", gender: "male", age: "young", accent: "korean",
    useCase: ["narration", "educational"], style: ["soft", "smooth", "playful"],
    description: "A silk-smooth young Korean male voice with a lightly teasing manner and an easy, well-travelled polish." },
  { id: "Junseo", gender: "male", age: "middle_aged", accent: "korean",
    useCase: ["narration", "educational"], style: ["soft", "warm", "calm"],
    description: "A tender Korean male voice with a patient, sing-song warmth that suits narration." },
  { id: "Aiman", gender: "male", age: "young", accent: "southeast_asian",
    useCase: ["social_media", "conversational"], style: ["friendly", "expressive", "energetic", "bright"],
    description: "An animated young Malay male voice with quick, unstudied delivery that lands well in social media." },
  { id: "Nurul", gender: "female", age: "young", accent: "southeast_asian",
    useCase: ["conversational", "social_media"], style: ["friendly", "warm", "soft"],
    description: "A tender young Malay female voice with a drifting flow that feels like being spoken to directly." },
  { id: "Linh", gender: "female", age: "young", accent: "southeast_asian",
    useCase: ["narration", "conversational"], style: ["calm", "soft", "friendly"],
    description: "A young Vietnamese female voice with a soft, unhurried tone for storytelling." },
  { id: "Bayu", gender: "male", age: "middle_aged", accent: "southeast_asian",
    useCase: ["conversational"], style: ["soft", "smooth"],
    description: "A smooth, softly weighted Indonesian male voice that speaks slowly and puts listeners at ease." },
  { id: "Rizky", gender: "male", age: "young", accent: "southeast_asian",
    useCase: ["social_media", "conversational"], style: ["energetic", "bright"],
    description: "A crisp young Indonesian male voice with a laid-back confidence that suits chatty video formats." },
  { id: "Wahyu", gender: "male", age: "middle_aged", accent: "southeast_asian",
    useCase: ["narration", "educational", "conversational"], style: ["calm", "soft"],
    description: "A soft Indonesian male voice with a patient, even manner that explains things without hurrying." },
  { id: "Gilang", gender: "male", age: "middle_aged", accent: "southeast_asian",
    useCase: ["narration", "entertainment", "conversational", "social_media"], style: ["confident", "soft", "playful"],
    description: "A soft, self-assured Indonesian male voice with a teasing streak that shifts easily between registers." },
  { id: "Maricel", gender: "female", age: "middle_aged", accent: "southeast_asian",
    useCase: ["entertainment", "conversational", "social_media"], style: ["friendly", "bright", "dramatic"],
    description: "A bright Filipino female voice with a flair for the dramatic and real conviction behind each line." },
  { id: "Budi", gender: "male", age: "old", accent: "southeast_asian",
    useCase: ["entertainment"], style: ["deep", "breathy", "expressive", "formal"],
    description: "A rasping, cavernous Indonesian male voice with an unsettling edge that also reads as elderly." },
  { id: "Mai", gender: "female", age: "young", accent: "southeast_asian",
    useCase: ["narration", "conversational"], style: ["soft", "friendly", "smooth"],
    description: "A barely-raised young Vietnamese female voice from the south, slow and quieting." },
  { id: "Huong", gender: "female", age: "middle_aged", accent: "southeast_asian",
    useCase: ["conversational", "educational", "narration"], style: ["friendly", "warm", "bright", "energetic"],
    description: "A bright, welcoming Vietnamese female voice from the south, articulate and easy to stay with over long stretches." },
];

/** Every accent present in the roster, sorted. The picker builds its filter
 *  from this rather than a hardcoded list, so a roster refresh that adds an
 *  accent needs no UI change — only a label (see sonioxFacetLabels). */
export const SONIOX_ACCENTS: string[] = ["african", "american", "arabic", "australian", "brazilian", "british", "chinese", "french", "german", "indian", "italian", "japanese", "korean", "latin_american", "portuguese", "slavic", "southeast_asian", "spanish"];

/** Every use-case tag present in the roster, sorted. */
export const SONIOX_USE_CASES: string[] = ["conversational", "educational", "entertainment", "narration", "social_media"];

/** Every style tag present in the roster, sorted. */
export const SONIOX_STYLES: string[] = ["breathy", "bright", "calm", "confident", "deep", "dramatic", "energetic", "expressive", "formal", "friendly", "neutral", "playful", "raspy", "smooth", "soft", "warm"];
