/**
 * What Soniox Text-to-Speech accepts: the model id, the built-in voice roster,
 * and the wire options that go with them.
 *
 * This module exists because `tts-rt-v1` → `tts-rt-v2` was not the drop-in the
 * vendor changelog promised. Soniox announced v2 as "fully compatible ... simply
 * replace the model name" (GA 2026-08-11, v1 removed 2026-08-31), but v2 drops
 * seven voices that v1 served — Claire, Elise, Jack, Maya, Meera, Noah, Sofia —
 * and rejects them with HTTP 400. Sokuji had the model id copied into five
 * modules and the default voice into four, so a rename-per-call-site migration
 * had five chances to miss one.
 *
 * A settings file written under v1 can still name one of the dropped voices.
 * That is deliberately not repaired here. The alternative — a rewrite table
 * mapping retired names onto a survivor — hides a roster change behind a silent
 * voice substitution, and has to be carried forever afterwards.
 *
 * What a stale name actually does depends on who is asking, because "not in
 * this roster" is also how the app recognizes a CLONED voice:
 *
 *  - BYOK: the name reaches the wire, Soniox answers 400, and the session
 *    degrades to subtitles the way any other TTS failure does.
 *  - Managed (Kizuna AI): MainPanel reads it as a cloned voice and runs the
 *    managed-voice preparation path first.
 *  - Settings: SonioxVoiceSection shows it as "(deleted voice)", never
 *    selectable. The delete affordance beside that row is managed-only
 *    (`removable: managed && !!source && managedListKnown`), so BYOK gets the
 *    label without a destructive action next to it.
 *
 * Only the first is a property of this module. The other two are the existing
 * "unknown id ⇒ cloned voice" heuristic meeting a roster that shrank, and they
 * behave that way for any name the roster does not list.
 *
 * The roster is a SNAPSHOT, not a contract — Soniox deleted the voice table
 * from its own docs in favour of an endpoint, and it moves: 71 voices at v2 GA
 * (2026-08-11), 70 hours later, 200 on 2026-09-10. It is no longer hand-copied
 * into this file: `sonioxVoiceRoster.ts` is generated by
 * `scripts/fetch-soniox-voices.mjs`, and SONIOX_VOICES below is derived from
 * it, so a refresh cannot leave a retired voice selectable.
 */
import type { VoiceOption } from '../../services/providers/ProviderConfig';
import { SONIOX_VOICE_ROSTER } from './sonioxVoiceRoster';

/** The only TTS model id Sokuji sends. Every call site imports this one. */
export const SONIOX_TTS_MODEL = 'tts-rt-v2';

/**
 * Shortens the pauses BETWEEN words without changing how fast the words
 * themselves are spoken (that is `speed`, and the two are independent).
 *
 * On by default because v2's natural pacing is slower than the v1 it replaces:
 * measured against v1 on identical text, voice and speed, v2 runs ~14% longer
 * with this off and ~7% shorter with it on. Leaving it off would have shipped
 * the upgrade as a pacing regression in a live-translation product — and, since
 * Soniox bills generated audio, a bill increase nobody asked for.
 */
export const SONIOX_REDUCE_SILENCE = true;

/** Present in the v2 roster, so it survives the migration. */
export const SONIOX_DEFAULT_VOICE = 'Adrian';

/**
 * Built-in voices, in the order Soniox returns them (grouped by accent family).
 *
 * DERIVED from the generated roster rather than listed here, so a voice cannot
 * outlive its presence at Soniox — which is exactly what went wrong before:
 * this file carried a hand-copied snapshot, Soniox retired `Hugo`, and the
 * picker kept offering a voice the TTS endpoint answers
 * `400 Invalid voice 'Hugo' for model 'tts-rt-v2'`.
 *
 * The richer metadata each voice carries (gender, age, accent, use-case and
 * style tags, description) lives on SONIOX_VOICE_ROSTER; this projection is
 * only what the provider descriptor's `voices` contract needs.
 */
export const SONIOX_VOICES: VoiceOption[] = SONIOX_VOICE_ROSTER.map((voice) => ({
  name: voice.id,
  value: voice.id,
}));
