import React from 'react';
import type { RecordingSummaryResult } from '../types/recording';
import { RecordingResultDialog } from './RecordingResultDialog';

const localized = (language: string, zh: string, ja: string, en: string) => language.startsWith('zh') ? zh : language.startsWith('ja') ? ja : en;

export function SummaryReportDialog({ result, onClose, onExport, language = 'zh' }: { result: RecordingSummaryResult; onClose: () => void; onExport: (type: 'report-txt' | 'report-docx') => void; language?: string }) {
  const text = [result.topic, ...result.conclusions, ...result.discussionPoints.map((item) => `${item.title}\n${item.content}`), ...result.actionItems.map((item) => item.task), result.keywords.join(' · ')].join('\n');
  return <RecordingResultDialog title={localized(language, '总结报告', '要約レポート', 'Summary report')} closeLabel={localized(language, '关闭', '閉じる', 'Close')} onClose={onClose}><section className="recording-summary-report"><h3>{localized(language, '主题', 'テーマ', 'Topic')}</h3><p>{result.topic}</p><h3>{localized(language, '核心结论', '主な結論', 'Key conclusions')}</h3><ul>{result.conclusions.map((item) => <li key={item}>{item}</li>)}</ul><h3>{localized(language, '讨论要点', '議論の要点', 'Discussion points')}</h3>{result.discussionPoints.map((item) => <article key={item.title}><h4>{item.title}</h4><p>{item.content}</p></article>)}<h3>{localized(language, '待办事项', 'アクション項目', 'Action items')}</h3><ul>{result.actionItems.map((item) => <li key={item.task}>□ {item.task}{item.owner && localized(language, `（负责人：${item.owner}）`, `（担当：${item.owner}）`, ` (Owner: ${item.owner})`)}{item.deadline && localized(language, `（截止：${item.deadline}）`, `（期限：${item.deadline}）`, ` (Due: ${item.deadline})`)}</li>)}</ul><h3>{localized(language, '关键术语', 'キーワード', 'Keywords')}</h3><p>{result.keywords.join(' · ')}</p></section><footer><button type="button" onClick={() => void navigator.clipboard.writeText(text)}>{localized(language, '复制全文', '全文をコピー', 'Copy all')}</button><button type="button" onClick={() => onExport('report-txt')}>{localized(language, '下载 TXT', 'TXT をダウンロード', 'Download TXT')}</button><button type="button" onClick={() => onExport('report-docx')}>{localized(language, '下载 Word', 'Word をダウンロード', 'Download Word')}</button></footer></RecordingResultDialog>;
}
