"""Bake native/src/ops/*.ops into one C++ translation unit (parsed at first use by
sk_ops_parse, so the text format stays the single source of truth) and emit one static_assert
per recording that its expansion over the widest fallback set fits SK_OP_COVERAGE_MAX.
usage: gen_ops_data.py <ops-dir> <out.cpp> <sk_ops_data.h path>"""
import pathlib
import sys

WIDEST_FALLBACK = 7   # len(RUNG_FALLBACK_DTYPES["q4_k_m"]) in sidecar/sokuji_sidecar/catalog.py — keep in sync

ops_dir, out, header = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), sys.argv[3]
files = sorted(ops_dir.glob("*.ops"))
lines = ['// GENERATED by cmake/gen_ops_data.py from src/ops/*.ops — do not edit.',
         f'#include "{header}"', '']
for f in files:
    body = [l for l in f.read_text(encoding="utf-8").splitlines() if l.startswith("op=")]
    weight = sum(1 for l in body if "WEIGHT" in l)
    expanded = weight * WIDEST_FALLBACK + (len(body) - weight)
    lines.append(f'static_assert({expanded} <= SK_OP_COVERAGE_MAX, "{f.name}: {expanded} expanded entries exceed SK_OP_COVERAGE_MAX");')
lines += ['', 'const sk_ops_blob sk_ops_blobs[] = {']
for f in files:
    stage, family = f.stem.split("-", 1)
    text = f.read_text(encoding="utf-8").replace("\\", "\\\\").replace('"', '\\"')
    body = "".join(f'    "{line}\\n"\n' for line in text.splitlines())
    lines.append(f'    {{ "{stage}", "{family}",\n{body}    }},')
lines += ['};', f'const int sk_ops_blob_count_ = {len(files)};', '']
out.write_text("\n".join(lines), encoding="utf-8")
print(f"gen_ops_data: {len(files)} recordings -> {out}")
